############################################################
#
# Dockerfile to build first Centos
# Based on Centos!
#
############################################################

# Pull base image.
# Usage: FROM [image name]
FROM ubuntu

# Usage: MAINTAINER [name]
MAINTAINER perezpardojc@gmail.com

# Install Nginx.
RUN \
  # add-apt-repository -y ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y nginx 	&& \
  apt-get install -y wget 	&& \
  apt-get install -y curl 	&& \
  apt-get install -y ntp 	&& \

  rm -rf /var/lib/apt/lists/* && \
  echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
  chown -R www-data:www-data /var/lib/nginx

# Define mountable directories.
VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Expose ports.
EXPOSE 80
EXPOSE 443

RUN echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' 
RUN echo 'we are RUNning some # of cool things' 
RUN echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~' 


#  docker build -t my_nginx .    
# docker run -d -p 80:80 my_nginx

# docker run -d -p 80:80 -v <sites-enabled-dir>:/etc/nginx/conf.d -v <certs-dir>:/etc/nginx/certs -v <log-dir>:/var/log/nginx -v <html-dir>:/var/www/html dockerfile/nginx

# docker run -d -p 80:80 -v /C/VM/volume/:/etc/nginx/conf.d -v /C/VM/volume/:/etc/nginx/certs -v /C/VM/volume/:/var/log/nginx -v /C/VM/volume/:/var/www/html nginx

# docker run -d -p 80:80 -v /C/VM/volume/:/var/log/nginx nginx

