############################################################
# Dockerfile to build Own Git server
# Based on 
############################################################

# Usage: FROM [image name]
FROM gogs/gogs

# Usage: MAINTAINER [name]
MAINTAINER perezpardojc@gmail.com

# Usage: VOLUME ["/dir_1", "/dir_2" ..]
VOLUME ["C:\Software\code\"]

# Usage: ADD [source directory or URL] [destination directory]
# ADD C:\\Software\\code\\ /gogs-data/ 

# Usage: WORKDIR /path
WORKDIR /gogs-data/


# Usage: EXPOSE [port]
EXPOSE 8022
EXPOSE 3000

# Copy app to /src
#COPY . /src
#CMD cd /src && node ./app.js
